name: Build and Upload Release Artifacts

on:
  release:
    types: [created, edited]  # 同时监听创建和编辑事件

permissions:
  contents: write  # 必需的上传权限

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'  # 推荐使用 LTS 版本
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package  # 生成 jar 包

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/*.jar
            target/*-sources.jar  # 可选：上传源码包
          tag_name: ${{ github.ref_name }}  # 自动使用当前 tag
